- name: Install Apache
  yum:
    name: "{{ package }}"
    state: present

- name: Enable Apache
  service:
    name: "{{ package }}" # Specify the service name directly
    state: started
    enabled: yes
