- name: Install Apache
  yum:
    name: "{{ packages }}"
    state: present

- name: Enable Apache
  service:
    name: "{{ packages }}" # Specify the service name directly
    state: started
    enabled: yes
